name: Build & Deploy Prod. Fine PyPI Package

on:
  push:
    branches:
      - 'releases/**'
  workflow_dispatch:

jobs:

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, macOS-10.15 ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.3.1 twine
      - name: Build wheels
        env:
          CIBW_BEFORE_BUILD: pip install numpy cython
          CIBW_SKIP: pp*
        run: python -m cibuildwheel --output-dir dist
      - name: Upload Wheels
        env:
          TWINE_USERNAME: ${{secrets.TWINE_USERNAME}}
          TWINE_PASSWORD: ${{secrets.TWINE_PASSWORD}}
        run: twine upload -u $TWINE_USERNAME -p $TWINE_PASSWORD
