name: Build & Deploy Test. Fine PyPI Package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build_package:
    name: Build PyPI Package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker Image
      run: docker build . --file Dockerfile --tag pypi-packager
    - name: Build the PyPI Package
      run: docker run --rm -v "${GITHUB_WORKSPACE}":/usr/src/app -w /usr/src/app pypi-packager python setup.py sdist bdist_wheel --version=0.0.1
    - name: Upload the PyPI Package
      env:
        TWINE_USERNAME: ${{secrets.TWINE_USERNAME}}
        TWINE_PASSWORD: ${{secrets.TWINE_PASSWORD}}
      run: docker run --rm -v "${GITHUB_WORKSPACE}":/usr/src/app -w /usr/src/app pypi-packager twine upload  --repository testpypi dist/*.tar.gz -u $TWINE_USERNAME -p $TWINE_PASSWORD
