name: Build & Deploy Test. Fine PyPI Package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, windows-2019, macOS-10.15 ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.3.1 twine
      - name: Build wheels
        env:
          CIBW_BEFORE_BUILD: pip install numpy cython
        run: python -m cibuildwheel --output-dir dist --CIBW_BEFORE_BUILD
      - name: Upload Wheels
        env:
          TWINE_USERNAME: ${{secrets.TWINE_USERNAME}}
          TWINE_PASSWORD: ${{secrets.TWINE_PASSWORD}}
        run: docker run --rm -v "${GITHUB_WORKSPACE}":/usr/src/app -w /usr/src/app pypi-packager twine upload  --repository testpypi dist/* -u $TWINE_USERNAME -p $TWINE_PASSWORD
